import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Header } from "@/components/Header";
import { CartProvider } from "@/components/providers/ZustandProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal?: React.ReactNode;
}>) {
  return (
    <CartProvider>
      <Header />
      {children}
      {modal}
      <footer className="border-t-1 m-auto max-w-screen-lg p-4 flex justify-center items-center">
        2024 © Sparta Shop
      </footer>
    </CartProvider>
  );
}
